apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: ""
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: 5.42.0
    chart: argo-cd
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
