apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: pro
            url: https://42e6578a-aeed-40bb-ad03-058c40858639.fr-par-2.linodelke.net:443
          - cluster: manager
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{`{{cluster}}`}}-kube-prometheus-stack"
    spec:
      project: default
      source:
        path: charts/kube-prometheus-stack
        repoURL: https://github.com/antonioarenzanapulido/kubernetes-cluster-basic-stack.git
        targetRevision: main
        helm:
          values: |
            kube-prometheus-stack:
              prometheus:
                prometheusSpec:
                  serviceMonitorSelector: {}
      destination:
        server: "{{`{{url}}`}}"
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
