apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki-promtail
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: pro
            url: https://42e6578a-aeed-40bb-ad03-058c40858639.fr-par-2.linodelke.net:443
          - cluster: manager
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{`{{cluster}}`}}-loki-promtail-stack"
    spec:
      project: default
      source:
        path: charts/loki-promtail
        repoURL: https://github.com/antonioarenzanapulido/kubernetes-cluster-basic-stack.git
        targetRevision: main
        helm:
          skipCrds: true
      destination:
        server: "{{`{{url}}`}}"
        namespace: log-ingestion
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
