kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      # serviceMonitorSelector: {} Passed as manual parameter to Application as ArgoCD skips empty objects from values.yaml
